server:
  port: 23234
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable_lecture?autoReconnect=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: foobared
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 3600
    password: foobared
    database: 10
    lettuce:
      pool:
        max-active: 500